CREATE TABLE IF NOT EXISTS apartments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  type TEXT NOT NULL,
  district TEXT NOT NULL,
  price INTEGER NOT NULL,
  area INTEGER NOT NULL,
  description TEXT NOT NULL,
  amenities TEXT NOT NULL,
  images TEXT NOT NULL,
  featured INTEGER NOT NULL DEFAULT 0,
  views INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
